# Generated by Django 6.0.2 on 2026-02-12 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InitialProjectModel',
            fields=[
                ('id', models.UUIDField(default='<function uuid4 at 0x10a5f2da0>', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'initial_projects',
            },
        ),
    ]
