# Generated by Django 6.0.2 on 2026-02-12 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initial_project_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initialprojectmodel',
            name='id',
            field=models.UUIDField(default='<function uuid4 at 0x10a5fada0>', primary_key=True, serialize=False),
        ),
    ]
