# Generated by Django 6.0.2 on 2026-02-16 03:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initial_project_app', '0002_alter_initialprojectmodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initialprojectmodel',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
